### ISSUE TITLE
I think you're not using the 'adam' optimizer local variable in algo-whiteboard-letter-embeddings-v1.ipynb

### ISSUE THREAD

**Issue by zbenmo** [RasaHQ/algorithm-whiteboard-resources#1]
It seems that you're using the built-in 'adam' as you pass a string.

**Comment by koaning** [comment]
Somebody on twitter also mentioned that. 

It deserves mentioning that it matters little, it's more out of habbit that I put it there.

Fair that I make the change here at least. On the TODO :)

**Comment by koaning** [comment]
colab is now fixed.

**Comment by koaning** [comment]
fixed.
